# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoArchetype < Formula
  desc "Dead simple project blueprints for the rest of us"
  homepage "https://github.com/rantav/go-archetype"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vyacheslavisaev/go-archetype/releases/download/v0.1.22/go-archetype_Darwin_arm64.tar.gz"
      sha256 "b3b32776d4040d20e4450c65f6448d04a1ed35a50ccb5b648d48edf349d4de08"

      def install
        bin.install "go-archetype"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vyacheslavisaev/go-archetype/releases/download/v0.1.22/go-archetype_Darwin_x86_64.tar.gz"
      sha256 "5e6b5ceb5f7b97e7d1fc58367b3ff563a53ac7b023d3615c2cd36e24895d3f33"

      def install
        bin.install "go-archetype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vyacheslavisaev/go-archetype/releases/download/v0.1.22/go-archetype_Linux_x86_64.tar.gz"
      sha256 "49824d390870dba7b2eb9e0009cad83f2e1bf69369e0a62094b3e44a396657f0"

      def install
        bin.install "go-archetype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vyacheslavisaev/go-archetype/releases/download/v0.1.22/go-archetype_Linux_arm64.tar.gz"
      sha256 "b3df70bdafe231743fe2895827692cc4c475e2912a53af656a722ba3de151165"

      def install
        bin.install "go-archetype"
      end
    end
  end
end
