# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoArchetype < Formula
  desc ""
  homepage "https://github.com/rantav/go-archetype"
  version "0.1.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/save-vi/go-archetype/releases/download/v0.1.20/go-archetype_Darwin_x86_64.tar.gz"
      sha256 "e7144c60479ff3226a96bdcecebf16333a6eff46b2898399580eb3d0eb29a21c"

      def install
        bin.install "go-archetype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/save-vi/go-archetype/releases/download/v0.1.20/go-archetype_Darwin_arm64.tar.gz"
      sha256 "3605c6e60e220150dc45818de273a2d47b61a6ee8cc55f921a5f7e5a7e68ee2e"

      def install
        bin.install "go-archetype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/save-vi/go-archetype/releases/download/v0.1.20/go-archetype_Linux_arm64.tar.gz"
      sha256 "9b34281f88242b711156fb9202a55a44928e7bd851b39602672bb3f05b118fc2"

      def install
        bin.install "go-archetype"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/save-vi/go-archetype/releases/download/v0.1.20/go-archetype_Linux_x86_64.tar.gz"
      sha256 "531ac9bd8b206532549a799d1ebeed1ef0c36eaa6c625a64d1e52bcd511e0c18"

      def install
        bin.install "go-archetype"
      end
    end
  end
end
